---
abstract: 'Modern UI redesign for Request Tracker 6'
author:
  - 'Torsten Brumm'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: gpl_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-Redesign
no_index:
  directory:
    - html
    - inc
    - po
    - static
    - t
requires:
  JSON: 0
  JSON::PP: 0
  LWP::UserAgent: 0
  XML::LibXML: 0
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: '0.15'
x_module_install_rtx_version: '0.45'
x_requires_rt: 6.0.2
x_rt_too_new: 7.0.0
